// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> _Texture;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{

	float2 uv = float2(id.xy/float2(512,424));
	float3 color = float3(uv,0);

    _Texture[id.xy] = float4(color, 0.0);
}
